### ISSUE TITLE
boolColumn instead of booColumn

### ISSUE THREAD

**Issue by MartinSStewart** [gicentre/tidy#1]
`booColumn` seems like an odd way to abbreviate boolean. Wouldn't `boolColumn` be a better choice? I think the meaning is much more clear and it's only one letter longer.

**Comment by jwoLondon** [comment]
Thanks for the suggestion. The rationale for `boo` is that it is consistent with related packages [elm-vega](https://package.elm-lang.org/packages/gicentre/elm-vega/latest/Vega#true) and [elm-vega-lite](https://package.elm-lang.org/packages/gicentre/elm-vegalite/latest/VegaLite#mBoo) that together abbreviate all core data types with three letters (`num`, `str` and `boo`) and use the three letter abbreviations consistently in function naming. 

I recognise the value in using the fuller name, but I am not sure the benefit outweighs the cost of inconsistency between packages. I guess a compromise might be to add an alias function `boolColumn`, although that could also be done by the package programmer.

**Comment by MartinSStewart** [comment]
That makes sense, thanks for the clarification. I don't think an alias is needed. The risk of confusing the user with two functions that do the same thing outweighs the benefit.

I'll close this issue since the current function name is probably the best choice.
